# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b61012c9b58335fc9701b0166297f5cac6acec94f80972b859174a333f72ef375abcb7916ac9d4ab1b3a8bc3c82101158cebeb1d7b3d00273a34bd062d006b11

test:
  secret_key_base: b0a6504d36f27aa98f9416cc93ba1fb8eaa3b3aafc2ccf05091a33dd7b9e61076ca14f93912636b11c6345e5fa5e424dec2f4a9aa43ae98564ddc9aea30cbfd4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
